---
# ------------------------------------------------------------------------------
# Role: datadog_setup
# Description: Installs the Datadog Agent in the k3s cluster to collect metrics, 
# logs, and traces for monitoring and observability. This role includes:
#   - Adding the Datadog Helm repository to the Helm configuration.
#   - Updating the Helm repositories to fetch the latest charts.
#   - Installing the Datadog Agent using the Helm chart, with custom values 
#     specified in the `datadog-values.yaml` file.
#
# This role is important for integrating Datadog into the cluster for full-stack 
# observability. The Datadog Agent collects and sends data to the Datadog service,
# enabling real-time monitoring of the infrastructure and applications.
# ------------------------------------------------------------------------------


- name: Add Datadog Helm repository
  command: helm repo add datadog https://helm.datadoghq.com

- name: Update Helm repositories
  command: helm repo update


- name: Install Datadog Agent via Helm (using Ansible module)
  kubernetes.core.helm:
    name: datadog
    chart_ref: datadog/datadog
    release_namespace: istio-system
    values: "{{ lookup('file', 'template/datadog-values.yaml') | from_yaml }}"
    state: present


# - name: Wait for Datadog Agent pod to be created
#   shell: |
#     kubectl get pods -n istio-system -l app=datadog --no-headers
#   register: datadog_pods_raw
#   retries: 10
#   delay: 10
#   until: datadog_pods_raw.stdout_lines | length > 0

# - name: Get Datadog Agent pod status
#   shell: |
#     kubectl get pods -n istio-system -l app=datadog -o jsonpath="{.items[0].status.phase}"
#   register: datadog_status
#   changed_when: false
#   failed_when: datadog_status.stdout not in ["Running", "Succeeded"]

# - name: Fail if Datadog Agent pod is not healthy
#   fail:
#     msg: "Datadog Agent pod is not in a healthy state. Current state: {{ datadog_status.stdout }}"
#   when: datadog_status.stdout not in ["Running", "Succeeded"]

