apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Values.gateway_name }}
  namespace: {{ .Values.global.namespace }} 
spec:
  selector:
    istio: ingressgateway  
  servers:
  - port:
      number: {{ .Values.service.port }} 
      name: {{ .Values.service.protocol_name }} 
      protocol: {{ .Values.service.protocol }} 
    hosts:
    - "{{ .Values.service.allowed_hosts }}"  
