apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngrok-tunnel
  namespace: istio-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ngrok
  template:
    metadata:
      labels:
        app: ngrok
    spec:
      containers:
      - name: ngrok
        image: ngrok/ngrok:latest
        env:
        - name: NGROK_AUTHTOKEN
          valueFrom:
            secretKeyRef:
              name: ngrok-secret
              key: NGROK_AUTHTOKEN
        args: ["http", "--region=eu", "istio-ingressgateway.istio-system.svc.cluster.local:80"]

