apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {}

    http {
      upstream python-web-app {
        server python-web-app-service:80;  # Points to the Python web app service
      }

      server {
        listen 80;
        server_name simple-nginx-deployment;  # Another virtual host

        location / {
          proxy_pass http://python-web-app;  # Proxy pass to the same upstream or different backend
        }
      }
    }
