apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-web
spec:
  replicas: 2  # We want to run 2 replicas of the web app
  selector:
    matchLabels:
      app: python-web  # The label used to identify pods
  template:
    metadata:
      labels:
        app: python-web
    spec:
      containers:
        - name: python-web
          image: tiangolo/uwsgi-nginx-flask:python3.8  # The image used for the container
          ports:
            - containerPort: 80  # Exposing port 80 on the container

---
apiVersion: v1
kind: Service
metadata:
  name: python-web-app-service
spec:
  selector:
    app: python-web # Service selector to match the app label
  ports:
  - protocol: TCP
    port: 80  # The port your service will expose
    targetPort: 80  # Port to target on the container
  type: ClusterIP  # Internal service within the cluster