
- name: Copy prometheus-pv.yaml to the target node
  copy:
    src: files/prometheus-pv.yaml
    dest: /tmp/prometheus-pv.yaml

- name: Copy prometheus-pvc.yaml to the target node
  copy:
    src: files/prometheus-pvc.yaml
    dest: /tmp/prometheus-pvc.yaml

- name: Apply PVC manifest using kubectl
  command: kubectl apply -f /tmp/prometheus-pv.yaml

- name: Apply PVC manifest using kubectl
  command: kubectl apply -f /tmp/prometheus-pvc.yaml


