
- name: Create PersistentVolume and PersistentVolumeClaim for Prometheus
  include_tasks: create_pv_pvc.yaml

- name: Add prometheus-community repo
  command: helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
  args:
    creates: /root/.cache/helm/repository/prometheus-community-index.yaml

- name: Update Helm repo
  command: helm repo update


- name: Copy prometheus-pvc.yaml to the target node
  copy:
    src: templates/prometheus-values.yaml
    dest: /tmp/prometheus-values.yaml

- name: Deploy Prometheus with NFS PVC
  community.kubernetes.helm:
    name: prometheus
    chart_ref: prometheus-community/kube-prometheus-stack
    release_namespace: "{{ k3s_namespace }}"
    values_files:
      - "/tmp/prometheus-values.yaml"




