apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudwatch-cert
  namespace: amazon-cloudwatch
data:
  tls-cert.pem: |
    -----BEGIN CERTIFICATE-----
    MIIDOTCCAiGgAwIBAgIUY0jdgWV+Lkp+0iHW8RGSRSnLcZ0wDQYJKoZIhvcNAQEL
    BQAwRTELMAkGA1UEBhMCQVUxEzARBgNVBAgMClNvbWUtU3RhdGUxITAfBgNVBAoM
    GEludGVybmV0IFdpZGdpdHMgUHR5IEx0ZDAeFw0yNTA0MTcyMzQxNDhaFw0yNjA0
    MTcyMzQxNDhaMEUxCzAJBgNVBAYTAkFVMRMwEQYDVQQIDApTb21lLVN0YXRlMSEw
    HwYDVQQKDBhJbnRlcm5ldCBXaWRnaXRzIFB0eSBMdGQwggEiMA0GCSqGSIb3DQEB
    AQUAA4IBDwAwggEKAoIBAQDM5D0ABQAoGGerGuc50/H1dUSPeSy2cTEaM+teMzEE
    /heuZl/jPtEeigCm+Y+dwtue1LbY7HUlRY8//ScfLOeLHxEeSXTNKpcwNLUsGe6e
    skZhBXlIph10OiAg+5OfPtAaz3SOxun/CdG0SED+7VKcy9EINvJ2FxAaPH4KO3fW
    dxu/o5ruVHBxaLIelWZ1R8Kd3n3Ja0EE11zR/5WrpK9a/i0jJtkIptThBKbGVdSn
    iumebksHHegOk4NEJGgN2zhypI0vCHzB86girQRrruowXzsWGrlD8mxgoY+JnKPh
    6KXFrihRV9FNdFe4ctNhZkS2kA+J87NXSaOn3U7UBMb9AgMBAAGjITAfMB0GA1Ud
    DgQWBBQVUhhhH1Dq8gjAGsWgaxnn+TLYnjANBgkqhkiG9w0BAQsFAAOCAQEAHBff
    wChL/fwAIH+0uCh90qY9ZBM/Ukizar94WlxV51qaIbx2FFc+lj1g5VIVDjxP52oJ
    5Ql6wYl9kW3JuvEElwZSxg9dhrCDHU16qhFW+JJ9XW2VC/IJNPNsICXaAID1ldF4
    HLbCZBHB94MJFOvJiKRSaEbw3u9pgdxuOf1kvj0s/AveNCCTfd/2qyRyEv6TRDrl
    aRLB/frRyszPzIw0JGD0E0o20uEy4aVKlRpSpOTZXwYqj3Uk51ePHXgP1vAKcaB/
    TUyqOoLStruyxRmLrRSsUmFIEftB56ahJovnePdn5YXWyicInxUXH1E9ukYOJIgR
    tDwCtk+FfcQs9fRvOg==
    -----END CERTIFICATE-----
  
  tls-key.pem: |
    -----BEGIN PRIVATE KEY-----
    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDM5D0ABQAoGGer
    Guc50/H1dUSPeSy2cTEaM+teMzEE/heuZl/jPtEeigCm+Y+dwtue1LbY7HUlRY8/
    /ScfLOeLHxEeSXTNKpcwNLUsGe6eskZhBXlIph10OiAg+5OfPtAaz3SOxun/CdG0
    SED+7VKcy9EINvJ2FxAaPH4KO3fWdxu/o5ruVHBxaLIelWZ1R8Kd3n3Ja0EE11zR
    /5WrpK9a/i0jJtkIptThBKbGVdSniumebksHHegOk4NEJGgN2zhypI0vCHzB86gi
    rQRrruowXzsWGrlD8mxgoY+JnKPh6KXFrihRV9FNdFe4ctNhZkS2kA+J87NXSaOn
    3U7UBMb9AgMBAAECggEADBmJcawZ7YQ9cQkacRuPXSnC9f8XsSF/nxbEVlCLG0qf
    HuU8Uej2hAltzu6LeOtWOWvB7Y8PPvd75XE/g3ONK/XWdrWrUGdsvMPMFDHm2dfY
    2KdwWWY39JJvLct1lRCqTP8F2N2t2WocyHsA3Z0pxQkzS7sk9+zWPlpmrheDdPaC
    Hh6DlowGLKfr3uPFLaNssaGfJBVyCOgPoNV2/12P+aqW2jnB4dW/ZQQnr1i/WhVo
    9iO6d4M8UKczmwtzRkjKGnKmmw30tQ3t50lnZAGPVdaDmN5l7+hoci3D96k09raW
    RzXlBQwNTca0JaomEdmyMBwHGb+lYPrwzBrEYSvcoQKBgQD2B5SyAlfcH4xoPS55
    B8ZV2uah6hMBGt1cn4FSdzbPwreR+jI1dt6xwZaePt0aYQA/Sis4WgY03+wDnltG
    iQffFIdiXA8AtlEM0WKxEJZog65R92jJZ4fJOFXLfTvO0eEgkESkHrrto9YzcVoI
    t6RzsLikwTUd/asnox15i5mHHQKBgQDVMd+JMEZItBSTpTNDY9ds22vTwYpY3FPj
    7Ux7ifwMIPYfSBHie/6ouCxanaKEverJ2CCSLCDbIAB/N8gmlHs3rw8ww34OW9xa
    xzlhbyyXm80CoHTdRTfMLbB6tttkTmKBEkcF1JUHIMMSk3E+8ndzJFp4gfPOPlRV
    Wnx/esXZYQKBgCDVPijLW0JLC4fVsmAAg51tix3MiSC6nxP/TVjeA/iR+cGHbC/q
    XynFtf4EUal1jHzlvwLUMMPZpjuNZIzzOJOyv6aGtpHXwtU9FDihCBGGkTrrE5bd
    NCfMVtbDLboaFDsuRZrJZxTTqoBO/j7vkwjFar7B8f7AnZi6kfJoiOKZAoGAWc6L
    gofiY4fwTw29HXs2aTW5I1eZBruxXwc8O6IxmY5c/2pllklzSfFjRby3lEFIYUR4
    2/pY0NWXP//ogU/0480LkhgXxsateVQI+OFTIH5SCvQ6pmcdDRaGC/txSby3Q/XG
    E0+sg3cqlW2ku8Z5yPgcYD0lzdB1yAq4/R5jr6ECgYEAyqrB5EZGjRnmQEROE5N0
    VKaZB73Cf3UV8rvd4pUtWNCpIvu7itO00YnvessDiSsY9/F81Jiv76JkD0TGOoUE
    fXFZnKVOaDBA2J9kjXKhJt7DHLdj2YMQuoGvxXLKchNJq0M247NZORvqBsLZxpHp
    0BEeXtPwSH35TfSvdsKo7MU=
    -----END PRIVATE KEY-----

  
  tls-ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDazCCAlOgAwIBAgIUGwRZipI0W48WXlslUM0BZQX3QvIwDQYJKoZIhvcNAQEL
    BQAwRTELMAkGA1UEBhMCQVUxEzARBgNVBAgMClNvbWUtU3RhdGUxITAfBgNVBAoM
    GEludGVybmV0IFdpZGdpdHMgUHR5IEx0ZDAeFw0yNTA0MTcyMzEwMTRaFw0yNjA0
    MTcyMzEwMTRaMEUxCzAJBgNVBAYTAkFVMRMwEQYDVQQIDApTb21lLVN0YXRlMSEw
    HwYDVQQKDBhJbnRlcm5ldCBXaWRnaXRzIFB0eSBMdGQwggEiMA0GCSqGSIb3DQEB
    AQUAA4IBDwAwggEKAoIBAQDgFMuQtXsBajbJFSRJrLSG3ksfaPxWzGCDjwLh/daH
    pyIIEiPlDEx+0ZVuKSdEeC88LFFB5iKKYfydrGi1I1+kLvVh0UrDsoqyklp+Q9Zy
    1htfzxD4GGi/K+oOxvBpkW4Tx7FwFmirsa4Lv6W0ZHV6dcZhoV55M8FS5su7FbLA
    y6WOuCyulORhNonRptxKQsJR6SnqL7UKDRknQzHtLfyVll7e921tA9f2X9TFJ8CN
    v3SPO7eh3f1u+Iov2mo5XXaFkYHhxIpTPPEhU13ENapyfzj4+xI5W+uqKR4R6l2C
    nFunPAQoT9hOYUOI2kOQdypgTT0O5OUck9qGAvUgBLtRAgMBAAGjUzBRMB0GA1Ud
    DgQWBBSYxK0XvVHhQSgeCtBSqUArCrabJTAfBgNVHSMEGDAWgBSYxK0XvVHhQSge
    CtBSqUArCrabJTAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQA/
    UVgnVCvigHhF9v5XmSTa7FcY9t5nSBs5uknuRI/7qw5H+kGglWheBUCGti72UK3O
    jMf6Ari+Sj5plxq7v/QJ6nNrwxfHi7GdUWJH6HVZytDI5VhTaib/+IorjaWacJIs
    4DdumRzRxYM6iJlj3mI6PoybaINTMV6xkeeiW/7WHp5QrAoZty25Rr92vFivH38I
    P0hGV5fO61a5cHPryKidbeoY7iSPgNWZibRNq8GKvzJNEonaiqftmWSwddcZ6lIa
    YBhGdRem1fj/KSy0qm22byQRg6g3g7I2zqTihzp9Q3dsOySTc0HvEaERzvMeDmpU
    RYQNUKefsmwVGCOCwMs9
    -----END CERTIFICATE-----
  server-cert.pem: |
    -----BEGIN CERTIFICATE-----
    MIIDOTCCAiGgAwIBAgIUJRp/1LKQi3/tFAOPYZ+vpPVXJdcwDQYJKoZIhvcNAQEL
    BQAwRTELMAkGA1UEBhMCQVUxEzARBgNVBAgMClNvbWUtU3RhdGUxITAfBgNVBAoM
    GEludGVybmV0IFdpZGdpdHMgUHR5IEx0ZDAeFw0yNTA0MTcyMzQ4NTdaFw0yNjA0
    MTcyMzQ4NTdaMEUxCzAJBgNVBAYTAkFVMRMwEQYDVQQIDApTb21lLVN0YXRlMSEw
    HwYDVQQKDBhJbnRlcm5ldCBXaWRnaXRzIFB0eSBMdGQwggEiMA0GCSqGSIb3DQEB
    AQUAA4IBDwAwggEKAoIBAQDLb8USobJD+tDFQrFsbEUsE5wkG10xABz8Q4Hjm7Lk
    EQJy8OCPAOF69o6wmrBaYL+ZWIMXcVtDU1HL1/9r2lnjQqabi7u+/mw3Lw83ldPB
    NMfIVbvneBhwzsVocbuIBWF4CWItlZiGJsf41Lj03lS/fyBeePrRAnF2d+RZcumd
    H4X0tpIhaqyJmwR2Bx+iV327MzFswbA2mAO55OHIXsy7ldaxP3vFBu/Nt3vbnkLQ
    Y5rwIkBxg6hfkf/YPp3IaxC1qtk2zsbADWLmZCFGtNCV/gR5kLcfaV+0t1tReGos
    7bcQOXoCe07r3davvtqgwbAUSv5tT/44CUPHASmKBe5BAgMBAAGjITAfMB0GA1Ud
    DgQWBBSznJ3ei0E1S8JwruVsMscvF/59uDANBgkqhkiG9w0BAQsFAAOCAQEAARq7
    DTGVKQLjzfi4FRIzxtVCQ/Cs5zeaZ8uv61K79ActmvR2IUvPd6J9Y2Cd3ppkX0Ts
    odHaXus3syNuIs7BcENBBRkupFCiGV6gwtTdC+bHAn9lYVNUOY++Hr/WUVqRp2fV
    VsJJf/4/j21qZ6KZTy5efQopXRgXH25NwvPleGthAxMGWH/g0jaNXKyRs6/5sxvp
    Z839SD3ZIB/g+3RpBdhenr9xMw/IOYjYMySc1abiEZxitrlZvfVesMzAE/Wl+C8e
    I2vufKg22d031ffCBYPdw8xxLlphzzx7ykcjiWrJlZeiMhYTuMj0iz40PB2Zo8V9
    LbyVLRRD14vcqVtQLQ==
    -----END CERTIFICATE-----

  server-key.pem: |
    -----BEGIN PRIVATE KEY-----
    MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDLb8USobJD+tDF
    QrFsbEUsE5wkG10xABz8Q4Hjm7LkEQJy8OCPAOF69o6wmrBaYL+ZWIMXcVtDU1HL
    1/9r2lnjQqabi7u+/mw3Lw83ldPBNMfIVbvneBhwzsVocbuIBWF4CWItlZiGJsf4
    1Lj03lS/fyBeePrRAnF2d+RZcumdH4X0tpIhaqyJmwR2Bx+iV327MzFswbA2mAO5
    5OHIXsy7ldaxP3vFBu/Nt3vbnkLQY5rwIkBxg6hfkf/YPp3IaxC1qtk2zsbADWLm
    ZCFGtNCV/gR5kLcfaV+0t1tReGos7bcQOXoCe07r3davvtqgwbAUSv5tT/44CUPH
    ASmKBe5BAgMBAAECggEAK3yetqsgcXYn0wb86MWjKrcdaT19OAiDaaxfk2E4xhZZ
    vOq/QeppCLE0Us2aVZN5WYUJbsUxQkzI/ydSxwITtWgNt9HQphT6WniBivsI2zPW
    Yf1rr6DlLpYQrlEjioHF8lQlK8Pe6QxYslj8mYF+Qboh1/gJ+4xHZ1DdG/7br9WH
    6YA2Qe6gIMH9cNuiqUXzcnzKOTr3+8oy6vtEZtLW11yU9XohBymg+ir0TmxT8x7i
    e1Y+yB/rxHEI6BiSTmoitfpopHeLGsD+kJoax5bq0frDWo3vwxzcA3H3b/eNCD+3
    y3xTqRFzc+23jUv2JPI0N91H/QjE49X+jyqiwuKa/QKBgQDmkXujzjgJyCUPNZp6
    CShpGTKdqI18NVrmgabQZwNjDpAezWchL/JU/XLPmBo3UlSZcDn+TRLkzyZ/6AyA
    +OPt/Y0h9SVmNnyKIiZoVed2T0amujT3D2gyoahyMZtFGIHdtZAx9/49i/Hn5C5R
    /ochVOzSqI5A9m74BnbZquXppQKBgQDh4CyH+xf0hMfvO7exGUaH4ZhCHpKcKOz9
    VDKfIJTuPi4vGy5A6WRnNmagNJMb+LuLL/4TLnSOw9T0hGLgpka0fZMERxAKqy2p
    JfTQESNp+/wVLCiu70UL8FMyYnw1L+QhQdfq6nUXToNLMOabtDVNCfFNyvvAFjWi
    Bgpe1AM3bQKBgDEjSjVTyq+S/wrpwp1FfF5Bp37gIB8bg97iPLnnalpfDSnzXoo9
    HKkuRpylbtjha/Qzbbiblm47E5poytllsbXTtpNJGopZDFuoAYV04VpedNEtmAIb
    P3qi5zJHDi9AlNS6UBvGHWHihFCGWbTRyNy6q6oNkBuaKXYkconbGRqdAoGALZLU
    iU8xQyWzTWKoKnRmFa5/0P9oJ1fekTJ20EJ7qiIjoV+DkpdEqcqBJFvXPrKN7IRv
    aCFcZR3ADuHTLW5/H5Winx9TbkOhf9pnrb93fL/Z2c/CGaGvNbx0nNrgIr8Z8Vfe
    n8hUfbJarUYdkVbn1jZmWILXDqeshJdhakauq3UCgYAsWGiVPT2lE4HwiL5Rm/3H
    9d3DPaKfwfL+CXzhNdlCW72iDrq/LyMPoA1HEzgM9Qk1Zonm414dcigW6C/OVPWq
    uHWK0coDWPx4bnc6zKn1R2w25p1lj1jQGlpDAyzknqX4f/hPcbVAz5xbjv6YvoK1
    qmFmJLYQTbO1CMTx1BQiPw==
    -----END PRIVATE KEY-----

  




--
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudwatch-agent-config
  namespace: amazon-cloudwatch
data:
  cloudwatch-agent-config.json: |
    {
      "agent": {
        "debug": true,
        "region": "us-east-1",
        "metrics_collection_interval": 60
      },
      "logs": {
        "logs_collected": {
          "files": {
            "collect_list": [
              {
                "file_path": "/var/log/syslog",
                "log_group_name": "syslog",
                "log_stream_name": "local-instance-{hostname}",
                "timezone": "UTC"
              },
              {
                "file_path": "/var/log/messages",
                "log_group_name": "messages",
                "log_stream_name": "local-instance-{hostname}",
                "timezone": "UTC"
              }
            ]
          }
        }
      },
      "tls": {
        "ca_file": "/etc/amazon-cloudwatch-observability-agent-client-cert/tls-cert.pem",
        "cert_file": "/etc/amazon-cloudwatch-observability-agent-client-cert/tls-cert.pem",
        "key_file": "/etc/amazon-cloudwatch-observability-agent-client-cert/tls-key.pem"
      },
      "metrics": {
        "metrics_collected": {
          "cpu": {
            "measurement": [
              "cpu_usage_idle",
              "cpu_usage_iowait"
            ],
            "metrics_collection_interval": 60
          },
          "disk": {
            "measurement": [
              "disk_free",
              "disk_used"
            ],
            "metrics_collection_interval": 60
          }
        }
      }
    }