# Post k3s install - Setup Istio and deploy manifests
# ---------------------------------------------------------------------
# This playbook runs after the k3s Kubernetes cluster has been installed.
# It deploys an example microservice stack enhanced with observability tooling
# using Helm for automation and configuration management.

# Components Installed:
# - Istio (service mesh for traffic control, observability, and security)
# - A Python sample application instrumented with APM
# - Nginx (acting as a reverse proxy )
# - Grafana (metrics visualization via Prometheus data source)
# - Datadog Agent (monitoring, logging, and tracing for full observability)

# Assumptions:
# - The k3s cluster is already up and running
# - Inventory specifies the correct IPs of target nodes
# - Helm repositories are configured during setup
# - All needed variables are correctly configured in the group_vars/all.yml

# Roles:
# - helm_setup: Installs and configures Helm CLI
# - istio_install: Deploys Istio using Helm and sets up ingress gateway
# - grafana_setup: Installs Grafana
# - deploy_helm: Renders templates and deploys apps using a custom Helm chart
# - datadog_setup: Installs the Datadog Agent with support for Istio and APM
# - prometheus_setup: (optional) Installs Prometheus for metrics collection
# - ngrok_setup: (optional) Exposes local services over secure tunnels

- name: Post k3s install - Setup Istio and deploy manifests
  hosts: server
  become: yes
  vars:
    istio_version: "{{ istio.version }}"
    istio_dir: "/tmp/istio-{{ istio_version }}"
    ansible_roles_path: "{{ playbook_dir }}/../roles"
  vars_files:
    - "{{ playbook_dir }}/../group_vars/vault.yml"
    - "{{ playbook_dir }}/../group_vars/all.yml"
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
  roles:
    - role: roles/helm_setup
    - role: roles/istio_install
    - role: roles/grafana_setup
    - role: roles/deploy_helm
    - role: roles/datadog_setup
    - role: roles/prometheus_setup
