---  
# Post k3s install - Setup Istio and deploy manifests
# ---------------------------------------------------
# This playbook is executed after the initial setup of k3s cluster is complete.
# It sets up various components necessary for running a sample application
# with observability features.

# Components Deployed:
# - Istio (for service mesh and traffic management)
# - A sample Python application with an APM agent for tracing
# - Nginx as a reverse proxy for routing external traffic to internal services
# - Prometheus and Grafana for metrics collection and visualization
# - Datadog agent for enhanced monitoring and observability

# Playbook Assumptions:
# - Target hosts have k3s installed and running
# - KUBECONFIG is set to use the local k3s configuration
# - Inventory file is updated with the servers'IP

# Roles used:
# - helm_setup: Installs Helm
# - istio_install: Installs Istio and sets up necessary CRDs
# - grafana_setup: Installs Grafana via Helm, configures Prometheus as a data source, and imports a predefined dashboard
# - deploy_manifests: Deploys application and Nginx reverse proxy
# - prometheus_setup: Installs Prometheus for monitoring
# - datadog_setup: Installs Datadog agent for observability

- name: Post k3s install - Setup Istio and deploy manifests
  hosts: server
  become: yes
  vars:
    istio_version: "1.22.0"
    istio_dir: "/tmp/istio-{{ istio_version }}"
    ansible_roles_path: "{{ playbook_dir }}/../roles"
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
  roles:
    - role: roles/helm_setup
    - role: roles/istio_install
    - role: roles/grafana_setup
    - role: roles/deploy_manifests
    - role: roles/prometheus_setup
    - role: roles/datadog_setup
