---  
- name: Post k3s install - Setup Istio and deploy manifests
  hosts: server
  become: yes
  vars:
    istio_version: "1.22.0"
    istio_dir: "/tmp/istio-{{ istio_version }}"
    ansible_roles_path: "{{ playbook_dir }}/../roles"
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
  roles:
    - role: roles/helm_setup
    - role: roles/istio_install
    - role: roles/grafana_setup
    - role: roles/deploy_manifests
    - role: roles/prometheus_setup
    - role: roles/datadog_setup
