---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.label.nginx_load_balancer }}
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: {{ .Values.label.app }}  
  ports:
  - protocol: {{ .Values.service.protocol }}  
    port: {{ .Values.global.port.nginx_load_balancer }}  
    targetPort: {{ .Values.global.port.nginx_load_balancer }}
  type: {{ .Values.service.type }}    