# ------------------------------------------------------------------------------
# Role: deploy_manifests
# Description: Deploys various Kubernetes manifests to the cluster. This includes:
#   - Copying the manifest files for deployment, including:
#       - Python app deployment with APM agent
#       - Nginx configuration and deployment for reverse proxy
#       - Istio gateway and virtual service configurations
#   - Applying the manifest files to the cluster using kubectl.
#   - Waiting for the istio pods to roll out and become ready.
#   - Verifying that the required deployments (`nginx-load-balancer` and `python-sample`) are created and running.
#
# This role is essential for deploying the sample application, its dependencies, 
# and ensuring that the correct Kubernetes resources are in place for both
# the application and Istio's ingress and service mesh functionality.
# ------------------------------------------------------------------------------


- name: Copy manifest files
  copy:
    src: "{{ playbook_dir }}/../roles/deploy_manifests/files/{{ item }}"
    dest: "/tmp/{{ item }}"
  loop:
    - nginx-config.yaml
    - nginx-deployment.yaml
    - virtualservice.yaml
    - istio-gateway.yaml
    - python-app-with-apm.yaml

- name: Apply manifests
  shell: |
    kubectl apply -f python-app-with-apm.yaml
    kubectl apply -f nginx-config.yaml
    kubectl apply -f nginx-deployment.yaml
    kubectl apply -f istio-gateway.yaml
    kubectl apply -f virtualservice.yaml
  args:
    chdir: /tmp

- name: Wait for app pods to be ready
  shell: |
    kubectl rollout status deployment istio-ingressgateway -n istio-system
    kubectl rollout status deployment istiod -n istio-system

- name: Get Kubernetes deployments using kubectl
  command: kubectl get deployments -n istio-system -o json
  register: result
  changed_when: false

# - name: Display Kubernetes deployments
#   debug:
#     var: result

- name: Verify specific deployments are created
  assert:
    that:
      - "'nginx-load-balancer' in result.stdout | from_json | json_query('items[].metadata.name')"
      - "'python-sample' in result.stdout | from_json | json_query('items[].metadata.name')"
    fail_msg: "One or more required deployments were not created"
    success_msg: "All required deployments were successfully created"


