- name: Install apt dependencies
  apt:
    name:
      - apt-transport-https
      - curl
      - gnupg
    state: present
    update_cache: yes

- name: Add Helm GPG key
  shell: curl https://baltocdn.com/helm/signing.asc | apt-key add -

- name: Add Helm APT repo
  shell: echo "deb https://baltocdn.com/helm/stable/debian/ all main" | tee /etc/apt/sources.list.d/helm-stable-debian.list

- name: Update apt and install Helm
  apt:
    name: helm
    state: present
    update_cache: yes

